version: '3.2'

services:
  backend:
    image: server:dev
    container_name: backend_test
    ports:
      - "8080:8080"

  frontend:
    depends_on:
      - backend
    image: client:dev
    container_name: frontend_test
    ports:
      - "3000:3000"
    tty: true
